# Generated by Django 5.1.4 on 2024-12-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='allergen_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recipe', models.TextField()),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='dish_images/')),
                ('diet_plan', models.CharField(choices=[('balanced', 'Balanced Diet'), ('keto', 'Keto'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('paleo', 'Paleo')], default='balanced', max_length=20)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('portion_size', models.FloatField()),
                ('allergens', models.ManyToManyField(blank=True, to='dishes.allergen')),
            ],
        ),
    ]
