# Generated by Django 5.1.4 on 2025-01-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='diet_plan',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='portion_size',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='protein',
        ),
        migrations.AddField(
            model_name='dish',
            name='meal_category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='meal_type',
            field=models.CharField(choices=[('meal', 'Meal'), ('snack', 'Snack')], default='meal', max_length=10),
        ),
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_plan', models.CharField(choices=[('low_carb', 'Low Carb'), ('balanced', 'Balanced Diet'), ('vegetarian', 'Vegetarian'), ('muscle_gain', 'Muscle Gain')], max_length=20)),
                ('size', models.CharField(choices=[('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'X-Large'), ('xxlarge', 'XX-Large')], max_length=10)),
                ('menu', models.CharField(choices=[('main', 'Main Menu'), ('vegetarian', 'Vegetarian Menu'), ('kids', 'Kids Menu')], max_length=20)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_infos', to='dishes.dish')),
            ],
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
    ]
