# Generated by Django 5.1.4 on 2025-01-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
