# Generated by Django 5.1.4 on 2024-12-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
        ('patients', '0002_patientprofile_delete_healthdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Menu date')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='dishes.dish')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
